# Generated by Django 6.0 on 2026-02-05 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Propietario', 'Propietario'), ('Admin', 'Admin'), ('Gerente', 'Gerente'), ('Personal', 'Personal'), ('user', 'User'), ('Developer', 'Developer'), ('Admin-Propietario', 'Admin-Propietario')], default='user', max_length=20, unique=True, verbose_name='Rol del usuario')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('default', models.BooleanField(default=False, verbose_name='Rol por defecto')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': '2-Roles',
                'db_table': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre de usuario')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Usuario activo?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='¿Tiene permisos de staff?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='¿Es superusuario?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.roles', verbose_name='Rol usuario')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': '1-Users',
                'db_table': 'Users',
                'ordering': ['-is_superuser'],
            },
        ),
    ]
