# Generated by Django 6.0 on 2026-02-13 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_infopersonal_users_personalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiudadesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(choices=[('Santa Cruz de la Sierra', 'Santa Cruz'), ('El Alto', 'El Alto'), ('La Paz', 'La Paz'), ('Cochabamba', 'Cochabamba'), ('Oruro', 'Oruro'), ('Sucre', 'Sucre'), ('Tarija', 'Tarija'), ('Potosí', 'Potosí'), ('Sacaba', 'Sacaba'), ('Quillacollo', 'Quillacollo'), ('Montero', 'Montero'), ('Trinidad', 'Trinidad'), ('Yacuiba', 'Yacuiba'), ('Riberalta', 'Riberalta'), ('Warnes', 'Warnes'), ('La Guardia', 'La Guardia'), ('Viacha', 'Viacha'), ('Colcapirhua', 'Colcapirhua'), ('Tiquipaya', 'Tiquipaya'), ('Cobija', 'Cobija'), ('Guayaramerín', 'Guayaramerín'), ('Villazón', 'Villazón'), ('Yapacaní', 'Yapacaní'), ('Bermejo', 'Bermejo'), ('Camiri', 'Camiri'), ('Tupiza', 'Tupiza'), ('Llallagua', 'Llallagua'), ('San Borja', 'San Borja'), ('Cotoca', 'Cotoca'), ('Villa Yapacaní', 'Villa Yapacaní'), ('Santiago del Torno', 'Santiago del Torno'), ('Huanuni', 'Huanuni'), ('Punata', 'Punata'), ('Ascención de Guarayos', 'Ascención de Guarayos')], default='Ascención de Guarayos', verbose_name='Ciudad')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': '8-Ciudad',
                'verbose_name_plural': '8-Ciudades',
                'db_table': 'Ciudades',
            },
        ),
        migrations.AlterField(
            model_name='infopersonal',
            name='ciudad',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.ciudadesmodel', verbose_name='Ciudad'),
        ),
    ]
