# Generated by Django 6.0 on 2026-02-13 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_ciudadesmodel_alter_infopersonal_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopersonal',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.ciudadesmodel', verbose_name='Ciudad'),
        ),
    ]
