# Generated by Django 6.0 on 2026-02-05 10:10

import Productos.models.producto_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Categoría')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('descripcion', models.TextField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('creado', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': '2-Categorias',
                'db_table': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='ProveedorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpresa', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Empresa')),
                ('nombreProveedor', models.CharField(help_text='Proveedor', max_length=50, verbose_name='Nombre')),
                ('apellidosProveedor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección completa')),
                ('descripcion', models.TextField(blank=True, help_text='Breve descripción de los servicios del proveedor', max_length=500, null=True, verbose_name='Descripción')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('fechaContratacion', models.DateField(auto_now=True, verbose_name='Fecha de contratación')),
                ('fechaDeExtincionDeContrato', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de extinción del contrato')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': '4-Proveedores',
                'db_table': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='ProductoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=20, unique=True, verbose_name='Slug')),
                ('precioCompra', models.PositiveIntegerField(validators=[Productos.models.producto_model.validarPrecio], verbose_name='Precio de compra')),
                ('precioVenta', models.PositiveIntegerField(validators=[Productos.models.producto_model.validarPrecio], verbose_name='Precio de compra')),
                ('marca', models.CharField(max_length=20, unique=True, verbose_name='Marca')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='Productos.categoriasmodel')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Productos.proveedormodel', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': '1-Productos',
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='InventarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockEnTienda', models.PositiveIntegerField(verbose_name='Stock em tienda')),
                ('stockEnAlmacen', models.PositiveIntegerField(verbose_name='Stock em almacén')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='Productos.productomodel', verbose_name='Producto asociado')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': '5-Inventario',
                'db_table': 'Inventario',
            },
        ),
        migrations.CreateModel(
            name='ImagenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre de la imágen')),
                ('imagen', models.ImageField(upload_to='images/')),
                ('producto', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.productomodel', verbose_name='Producto asociado')),
            ],
            options={
                'verbose_name': 'Imágen',
                'verbose_name_plural': '3-Imágen Producto',
                'db_table': 'ImágenesProductos',
            },
        ),
    ]
