# Generated by Django 6.0 on 2026-02-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomodel',
            name='nombre',
            field=models.CharField(default=1, error_messages={'max_length': 'Superaste el máximo permitido de carácteres', 'required': 'Por favor el nombre del producto es un campo obligatorio'}, help_text='Campo obligatorio', max_length=30, unique=True, verbose_name='Nombre del producto'),
            preserve_default=False,
        ),
    ]
