# Generated by Django 6.0 on 2026-02-05 10:37

import Productos.models.producto_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_productomodel_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomodel',
            name='precioCompra',
            field=models.FloatField(validators=[Productos.models.producto_model.validarPrecio], verbose_name='Precio de compra'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='precioVenta',
            field=models.FloatField(validators=[Productos.models.producto_model.validarPrecio], verbose_name='Precio de compra'),
        ),
    ]
