# Generated by Django 6.0 on 2026-02-05 11:52

import Productos.models.producto_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_alter_productomodel_precioventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomodel',
            name='precioCompra',
            field=models.FloatField(validators=[Productos.models.producto_model.validarPrecio], verbose_name='Precio de compra (Bs)'),
        ),
        migrations.AlterField(
            model_name='productomodel',
            name='precioVenta',
            field=models.FloatField(validators=[Productos.models.producto_model.validarPrecio], verbose_name='Precio de venta (Bs)'),
        ),
    ]
