# Generated by Django 6.0 on 2026-02-11 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_alter_productomodel_preciocompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenmodel',
            name='producto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='Productos.productomodel', verbose_name='Producto asociado'),
        ),
        migrations.AlterField(
            model_name='inventariomodel',
            name='stockEnAlmacen',
            field=models.PositiveIntegerField(verbose_name='Stock en almacén'),
        ),
        migrations.AlterField(
            model_name='inventariomodel',
            name='stockEnTienda',
            field=models.PositiveIntegerField(verbose_name='Stock en tienda'),
        ),
    ]
