# Generated by Django 6.0 on 2026-02-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_alter_imagenmodel_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomodel',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Descripción'),
        ),
    ]
