# Generated by Django 6.0 on 2026-02-11 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_productomodel_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionesCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Sección')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Productos.categoriasmodel', verbose_name='¿A qué categoría pertenece la sección?')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'db_table': 'SecciónesPorCategoría',
            },
        ),
    ]
