# Generated by Django 6.0 on 2026-02-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0008_seccionescategoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccionescategoria',
            options={'verbose_name': '6-Sección', 'verbose_name_plural': '6-Secciones'},
        ),
    ]
