# Generated by Django 6.0 on 2026-02-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0009_alter_seccionescategoria_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionescategoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagesSecciones/'),
        ),
    ]
