# Generated by Django 6.0 on 2026-02-19 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0010_seccionescategoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomodel',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Productos.seccionescategoria'),
        ),
    ]
