# Generated by Django 6.0 on 2026-02-19 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0011_productomodel_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionescategoria',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.productomodel'),
        ),
    ]
