# Generated by Django 6.0 on 2026-02-19 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0012_seccionescategoria_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomodel',
            name='imagen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Productos.imagenmodel'),
        ),
    ]
