# Generated by Django 6.0 on 2026-02-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0013_productomodel_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productomodel',
            name='imagen',
        ),
    ]
