# Generated by Django 6.0 on 2026-02-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0014_remove_productomodel_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomodel',
            name='marca',
            field=models.CharField(max_length=20, verbose_name='Marca'),
        ),
    ]
