# Generated by Django 6.0 on 2026-02-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0015_alter_productomodel_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenmodel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
